#nullable enable
using System.Collections;
using System.IO;
using NUnit.Framework;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;
using UnityEngine.TestTools;

namespace GameCanvas.Editor.Tests
{
    public class AssetCatalogTest
    {
        const string Root = "Assets/Res/__GcCatalogTests";
        [SetUp] public void SetUp()
        {
            Assert.That(Directory.Exists(Root), Is.False, "既存素材を保全するため中止");
            AssetDatabase.CreateFolder("Assets/Res", "__GcCatalogTests");
            AssetDatabase.CreateFolder(Root, "a"); AssetDatabase.CreateFolder(Root, "b");
        }
        [TearDown] public void TearDown()
        {
            AssetDatabase.DeleteAsset(Root);
            if (Directory.Exists(Root)) Directory.Delete(Root, true);
            AssetDatabase.Refresh();
            GcAssetCatalogBuilder.Refresh();
        }
        void AddImage(string relative)
        {
            File.Copy("Assets/Res/BallRed.png", Root + "/" + relative);
            AssetDatabase.ImportAsset(Root + "/" + relative, ImportAssetOptions.ForceSynchronousImport);
        }
        [Test] public void SameBasename_UsesDistinctPathsWithoutGeneratingCSharp()
        {
            var sources = Directory.GetFiles("Assets/GameCanvas/AutoGeneratedScripts", "*.cs");
            var before = System.Array.ConvertAll(sources, File.ReadAllText);
            AddImage("a/日本語 1.png"); AddImage("b/日本語 1.png");
            GcAssetCatalogBuilder.Refresh();
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/a/日本語 1.png", out var a), Is.True);
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/b/日本語 1.png", out var b), Is.True);
            Assert.That(a, Is.Not.EqualTo(b));
            CollectionAssert.AreEqual(before, System.Array.ConvertAll(sources, File.ReadAllText));
        }
        [Test] public void MoveAndDelete_RemoveOldKey()
        {
            AddImage("a/image.png"); GcAssetCatalogBuilder.Refresh();
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/a/image.png", out _), Is.True);
            Assert.That(AssetDatabase.MoveAsset(Root + "/a/image.png", Root + "/b/moved.png"), Is.Empty);
            GcAssetCatalogBuilder.Refresh();
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/a/image.png", out _), Is.False);
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/b/moved.png", out _), Is.True);
            AssetDatabase.DeleteAsset(Root + "/b/moved.png"); GcAssetCatalogBuilder.Refresh();
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/b/moved.png", out _), Is.False);
        }
        [Test] public void UnsupportedAsset_InvalidatesOldCatalogAndBlocksBuild()
        {
            AssetDatabase.CreateAsset(new Texture2D(4, 4), Root + "/native.asset");
            Assert.Throws<BuildFailedException>(() => GcAssetCatalogBuilder.Refresh());
            Assert.That(GcAssets.TryGetImage("BlueSky.png", out _), Is.False, "古いカタログで成功したように動かしてはいけない");
        }
        [Test] public void TextAndSound_AreAvailableByPath()
        {
            File.WriteAllText(Root + "/日本語.txt", "日本語テキスト");
            AssetDatabase.ImportAsset(Root + "/日本語.txt", ImportAssetOptions.ForceSynchronousImport);
            GcAssetCatalogBuilder.Refresh();
            Assert.That(GcAssets.TryGetText("__GcCatalogTests/日本語.txt", out var text), Is.True);
            Assert.That(text, Is.EqualTo("日本語テキスト"));
            Assert.That(GcAssets.TryGetSound("Click1.wav", out var sound), Is.True);
            Assert.That(sound.Invalid, Is.False);
            Assert.That(GcAssets.TryGetText("missing.txt", out _), Is.False);
        }
        [UnityTest] public IEnumerator ImportAutomaticallyUpdatesCatalog()
        {
            AddImage("a/automatic.png");
            var deadline = EditorApplication.timeSinceStartup + 10;
            while (!GcAssets.TryGetImage("__GcCatalogTests/a/automatic.png", out _) && EditorApplication.timeSinceStartup < deadline)
                yield return null;
            Assert.That(GcAssets.TryGetImage("__GcCatalogTests/a/automatic.png", out _), Is.True);
        }
    }
}
